fix: ignore  RawKeyDownEvent for remove button press
danger-ahead/simple_chips_input pull request #4
Opened 2023-11-20 19:14 UTC by Thioby

This PR fixes bug presented in video:
https://github.com/danger-ahead/simple_chips_input/assets/8046733/0fceab6e-fa7b-4f5d-b21e-caf8d24f56ca

2023-11-21 11:21 UTC, danger-ahead commented
Will take a look shortly.

2023-11-21 19:51 UTC, danger-ahead commented on lib/src/simple_chips_input.dart
> +  final void Function(String)? onChipAdded;
Can you please add comments here, so it's easy for the devs to understand?
Adding a comment here also adds it to the API reference in pub dev

2023-11-21 19:52 UTC, danger-ahead requested changes
LGTM. Add some docs for the changes.

2023-11-22 10:40 UTC, Thioby commented on lib/src/simple_chips_input.dart
> +  final void Function(String)? onChipAdded;
done

2023-11-22 10:40 UTC, Thioby commented
Done, please release new version of lib :)

2023-11-22 20:03 UTC, danger-ahead approved these changes

2023-11-22 20:03 UTC, merged